# Generated by Django 5.0.1 on 2026-03-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_district_alter_userprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireport',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aireport',
            name='dosage',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aireport',
            name='is_cardamom',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aireport',
            name='medicines',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aireport',
            name='precautions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aireport',
            name='severity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aireport',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
    ]
