# Generated by Django 5.0.1 on 2026-03-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aireport_diagnosis_aireport_dosage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireport',
            name='expert_deep_dive',
            field=models.TextField(blank=True),
        ),
    ]
